id: P009207
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ8042
  title: ཕར་ཕྱིན་སྐབས་དང་པོའི་མཐའ་དཔྱོད་ཀྱི་མཆན་འགྲེལ་རྩོམ་འཕྲོ།
  author: ''
  volumes:
    5149f20b978d4efc9ce9e5a0b87e9c75:
      image_group_id: I1KG18827
      title: ''
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
